upstream men_backend {
    server 172.20.1.10:80 weight=1;
    server 172.20.1.11:80 weight=1 backup;
}

server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
    proxy_pass http://men_backend;
    }
}
